services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"  # Update the left side of this to change the host port
    environment:
      - PORT=8080  # Set the port for Flask server here
      - GRPC_PORT=50051  # Set the port for Flask server here
    depends_on:
      - vector_database

  vector_database:
    build:
      context: .
      dockerfile: vector_database/Dockerfile
    environment:
      - GRPC_PORT=50051  # Set the port for grPC server here
    volumes:
      - wordtopia_data:/vector_database/data

volumes:
  wordtopia_data:
    driver: local